<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.14159265359"/>

  <!-- Joints Control in Gazebo -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
  </gazebo>

  <!-- Geometrical properties -->
  <xacro:property name="link_side" value="0.02"/>
  <xacro:property name="joint_radius" value="0.018"/>
  <xacro:property name="joint_length" value="0.025"/>
  <xacro:property name="toe_length" value="0.03"/>
  <xacro:property name="foot_length" value="0.04"/>
  <xacro:property name="leg_length" value="0.40"/>
  <xacro:property name="arm_length" value="0.4"/>
  <!-- <xacro:property name="hand_length" value="0.04"/> -->
  <xacro:property name="finger_length" value="0.0"/>

  <!-- Materials -->
  <material name="orange">
    <color rgba="1.00 0.67 0.02 1.00"/>
  </material>

  <material name="gray">
    <color rgba="0.80 0.80 0.80 1.00"/>
  </material>

  <!-- Generates a box visual/collision/inertial -->
  <xacro:macro name="prism_vci" params="side length mass:=1 *origin">

    <xacro:macro name="prism_geometry">
      <xacro:insert_block name="origin"/>
      <geometry>
        <box size="${side} ${side} ${length}"/>
      </geometry>
    </xacro:macro>

    <visual>
      <xacro:prism_geometry/>
      <material name="orange"/>
    </visual>

    <collision>
      <xacro:prism_geometry/>
    </collision>

    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${(mass/12)*(side*side+length*length)}"
               iyy="${(mass/12)*(side*side+length*length)}"
               izz="${(mass/6)*(side*side)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>

  </xacro:macro>

  <!-- Generates a cylinder visual/collision -->
  <xacro:macro name="cylinder_vc" params="radius length *origin">

    <xacro:macro name="cylinder_geometry">
      <xacro:insert_block name="origin"/>
      <geometry>
        <cylinder length="${length}" radius="${radius}"/>
      </geometry>
    </xacro:macro>

    <visual>
      <xacro:cylinder_geometry/>
      <material name="gray"/>
    </visual>

    <collision>
      <xacro:cylinder_geometry/>
    </collision>

  </xacro:macro>

  <!-- Generates child joint of parent -->
  <xacro:macro name="arm_joint" params="child parent dist:=0 axis">

    <joint name="${parent}_${child}_joint" type="revolute">
      <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${axis}"/>
      <limit effort="40.0"
             velocity="1.0"
             lower="${-PI}"
             upper="${PI}"/>
    </joint>

    <!-- Required for ROS control -->
    <transmission name="${parent}_${child}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${parent}_${child}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${parent}_${child}_actuator"/>
    </transmission>

    <link name="${parent}">

      <xacro:prism_vci length="${dist}" side="${link_side}">
        <origin xyz="0 0 ${dist/2}" rpy="0 0 0"/>
      </xacro:prism_vci>

      <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">

        <xacro:if value="${axis=='0 0 1'}">
          <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
        </xacro:if>

        <xacro:if value="${axis=='1 0 0'}">
          <origin xyz="0 0 ${dist}" rpy="0 ${PI/2} 0"/>
        </xacro:if>

        <xacro:if value="${axis=='0 1 0'}">
          <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
        </xacro:if>

      </xacro:cylinder_vc>

    </link>

    <gazebo reference="${parent}">
      <material>Gazebo/Orange</material>
    </gazebo>

  </xacro:macro>

  <!-- World frame (for Gazebo) -->
  <link name="world"/>



  <joint name="world_ball_joint" type="floating">
    <parent link="world"/>
    <child link="ball"/>
  </joint>

  <link name="ball">
      <visual>
          <geometry>
            <sphere radius="0.05"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="green">
            <color rgba="0 1 0 1"/>
            </material>
          </geometry>
      </visual>
  </link>

  <transmission name="$ball_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="ball_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="ball_actuator"/>
  </transmission>


  <!-- Arm fixed to world frame  -->
  <joint name="world_foot_joint" type="fixed">
    <parent link="world"/>
    <child link="toe"/>
  </joint>

  <!-- Joints Chain -->
  <!--
  <xacro:arm_joint parent="toe" child="foot" axis="0 0 1" dist="${toe_length}"/>
  -->

  <joint name="toe_foot_joint" type="revolute">
    <origin xyz="0 0 ${toe_length}" rpy="0 0 ${-PI}"/>
    <parent link="toe"/>
    <child link="foot"/>
    <axis xyz="0 0 -1"/>
    <limit effort="40.0"
           velocity="1.0"
           lower="${-PI}"
           upper="${PI}"/>
  </joint>

  <!-- Required for ROS control -->
  <transmission name="$toe_foot_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="toe_foot_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="toe_foot_actuator"/>
  </transmission>

  <link name="toe">
      <xacro:prism_vci length="${toe_length}" side="${link_side}">
        <origin xyz="0 0 ${toe_length/2}" rpy="0 0 0"/>
      </xacro:prism_vci>

      <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
          <origin xyz="0 0 ${toe_length}" rpy="0 0 0"/>
    </xacro:cylinder_vc>
  </link>


  <!--
  <xacro:arm_joint parent="foot" child="leg" axis="1 0 0" dist="${foot_length}"/>
  -->

  <joint name="foot_leg_joint" type="revolute">
    <origin xyz="0 0 ${foot_length}" rpy="${PI/2} 0 0"/>
    <parent link="foot"/>
    <child link="leg"/>
    <axis xyz="-1 0 0"/>
    <limit effort="40.0"
           velocity="1.0"
           lower="${-PI}"
           upper="${PI}"/>
  </joint>

  <!-- Required for ROS control -->
  <transmission name="$foot_leg_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="foot_leg_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="foot_leg_actuator"/>
  </transmission>

  <link name="foot">
      <xacro:prism_vci length="${foot_length}" side="${link_side}">
        <origin xyz="0 0 ${foot_length/2}" rpy="0 0 0"/>
      </xacro:prism_vci>

      <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
          <origin xyz="0 0 ${foot_length}" rpy="0 ${PI/2} 0"/>
    </xacro:cylinder_vc>
  </link>


  <!--
  <xacro:arm_joint parent="leg" child="arm" axis="1 0 0" dist="${leg_length}"/>
  -->


  <joint name="leg_arm_joint" type="revolute">
    <origin xyz="0 0 ${leg_length}" rpy="0 0 0"/>
    <parent link="leg"/>
    <child link="arm"/>
    <axis xyz="-1 0 0"/>
    <limit effort="40.0"
           velocity="1.0"
           lower="${-PI}"
           upper="${PI}"/>
  </joint>

  <!-- Required for ROS control -->
  <transmission name="$leg_arm_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="leg_arm_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="leg_arm_actuator"/>
  </transmission>

  <link name="leg">
      <xacro:prism_vci length="${leg_length}" side="${link_side}">
        <origin xyz="0 0 ${leg_length/2}" rpy="0 0 0"/>
      </xacro:prism_vci>

      <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
          <origin xyz="0 0 ${leg_length}" rpy="0 ${PI/2} 0"/>
    </xacro:cylinder_vc>
  </link>



  <xacro:arm_joint parent="arm" child="finger" axis="0 0 1" dist="${arm_length}"/>

  <!-- <xacro:arm_joint parent="arm" child="finger" axis="1 0 0" dist="${hand_length}"/> -->

  <!-- End effector -->
  <link name="finger">
    <xacro:prism_vci length="${finger_length}" side="${link_side}">
      <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
    </xacro:prism_vci>
  </link>

  <gazebo reference="finger">
    <material>Gazebo/Red</material>
  </gazebo>

</robot>
